# Numpy: Package for Multidimensional array

## Vector(1d)
## Matrix(2d or 1d)

## Creat an array

In [3]:
import numpy as np

In [4]:
sample_list = [6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
matrix = ([1,2,3],[4,5,6],[7,8,9])
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
matrix1 = ([12,34,56,67],[12,56,78,97],[45,56,88,34],[54,67,87,90])
np.array(matrix1)

array([[12, 34, 56, 67],
       [12, 56, 78, 97],
       [45, 56, 88, 34],
       [54, 67, 87, 90]])

In [13]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [14]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [20]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [35]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [36]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [37]:
np.linspace(1,30,8)

array([ 1.        ,  5.14285714,  9.28571429, 13.42857143, 17.57142857,
       21.71428571, 25.85714286, 30.        ])

In [38]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [39]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [41]:
np.random.rand(2,4)

array([[0.23296456, 0.15406629, 0.98334645, 0.72997274],
       [0.69467145, 0.52699281, 0.59117035, 0.35048408]])

In [45]:
np.random.randn(2,4)

array([[ 2.93797892,  1.47793244, -1.57217774, -0.28008108],
       [-0.84831745, -0.7396754 ,  0.51768681,  1.16176766]])

In [50]:
np.random.randn(2,6)

array([[ 2.02932945,  0.03021514, -0.61815231, -0.51737158, -0.36962855,
         1.88138282],
       [-0.26995726, -1.12903415,  0.19003732, -1.01514698,  1.25460048,
        -0.48277138]])

In [53]:
np.random.randint(0,10,15)

array([9, 0, 0, 3, 1, 5, 2, 0, 0, 0, 8, 6, 6, 7, 8])

In [55]:
np.random.randint(10,100,15)

array([41, 34, 32, 38, 20, 65, 69, 23, 77, 76, 96, 82, 52, 53, 75])

In [56]:
np.random.randint(20,56,100)

array([20, 40, 43, 28, 29, 26, 48, 30, 43, 25, 45, 38, 47, 29, 28, 32, 54,
       24, 26, 25, 24, 38, 20, 30, 40, 37, 49, 21, 42, 31, 35, 26, 29, 40,
       39, 22, 36, 51, 39, 44, 40, 36, 51, 55, 35, 25, 31, 51, 33, 48, 54,
       23, 33, 36, 30, 32, 49, 48, 30, 54, 20, 31, 27, 42, 38, 39, 37, 45,
       43, 41, 54, 50, 52, 37, 28, 28, 55, 48, 28, 22, 46, 53, 49, 36, 53,
       33, 32, 34, 28, 35, 20, 50, 55, 26, 45, 51, 34, 30, 20, 23])

In [57]:
sample_array = np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [58]:
rand_array = np.random.randint(0,10,5)
rand_array

array([1, 3, 5, 9, 1])

In [59]:
sample_array.min()

2

In [61]:
rand_array.min()

1

In [62]:
sample_array.argmin()

0

In [63]:
rand_array.argmin()

0

In [64]:
rand_array.max()

9

In [65]:
rand_array.argmax()

3

In [66]:
sample_array.argmax()

17

In [67]:
sample_array.dtype

dtype('int32')

In [68]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [70]:
a.T

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
a=np.random.rand(2,3)
a

array([[0.49425987, 0.61011494, 0.4634031 ],
       [0.37544315, 0.50542747, 0.85009874]])

In [75]:
a.T

array([[0.49425987, 0.37544315],
       [0.61011494, 0.50542747],
       [0.4634031 , 0.85009874]])

In [15]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [16]:
sample_array = sample_array.reshape(3,6)
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [17]:
sample_array = sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [12]:
sample_array = sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [18]:
sample_array[1] = 100
sample_array

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [19]:
sample_array = np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [22]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [23]:
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [24]:
sample_array[:] = 1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

## Two-Dimensional array

In [25]:
import numpy as np

In [26]:
sample_matrix = np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [27]:
sample_matrix[2][2]

24

In [28]:
sample_matrix[1][2]

54

In [29]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [30]:
sample_matrix[1,1]

2

In [31]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [37]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [38]:
sample_matrix[2]

array([56, 76, 24,  7])

In [32]:
arr = np.arange(10,100)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [33]:
arr = arr.reshape(6,15)
arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
arr[1:3,2:4]

array([[27, 28],
       [42, 43]])

In [36]:
arr[3:8,3:6]

array([[58, 59, 60],
       [73, 74, 75],
       [88, 89, 90]])

#




In [48]:
sample_array = np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [50]:
sample_array+sample_array+sample_array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90])

In [51]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [52]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [58]:
np.log(sample_array) #Takes log with base e i.e ln

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [54]:
np.max(sample_array)

30

In [55]:
np.min(sample_array)

1

In [56]:
np.argmax(sample_array)

29

In [60]:
np.argmin(sample_array)

0

In [62]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [63]:
np.std(sample_array)

8.65544144839919

In [64]:
np.var(sample_array)

74.91666666666667

In [65]:
np.mean(sample_array)

15.5

In [66]:
array = np.random.randn(3,4) ### normal distribution
array

array([[ 0.54964126, -0.70480329,  0.15264946, -0.70401122],
       [ 0.11731408,  0.1405548 ,  0.5141277 ,  0.87026912],
       [ 0.65244489,  0.14115371, -0.35121232, -0.80379065]])

In [69]:
np.round(array,decimals=3)

array([[ 0.55 , -0.705,  0.153, -0.704],
       [ 0.117,  0.141,  0.514,  0.87 ],
       [ 0.652,  0.141, -0.351, -0.804]])

In [70]:
np.round(array,decimals=0)

array([[ 1., -1.,  0., -1.],
       [ 0.,  0.,  1.,  1.],
       [ 1.,  0., -0., -1.]])

In [72]:
sports = np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

# Pandas

In [1]:
import pandas as pd

In [5]:
import numpy as np

In [3]:
lables=['a','b','c','d']
lables

['a', 'b', 'c', 'd']

In [4]:
list=[10,28,3,4]
list

[10, 28, 3, 4]

In [6]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [7]:
dict={'w':10,'x':20,'y':30,'z':40}
dict

{'w': 10, 'x': 20, 'y': 30, 'z': 40}

In [8]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [9]:
pd.Series(data=list,index=lables)

a    10
b    28
c     3
d     4
dtype: int64

In [11]:
pd.Series(lables,list)

10    a
28    b
3     c
4     d
dtype: object

In [12]:
pd.Series(list,lables)

a    10
b    28
c     3
d     4
dtype: int64

In [13]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

## Pandas dataframe and indexing

In [15]:
sports1= pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [16]:
sports1['basketball']

3

In [18]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [19]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [20]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.624646  0.817689  0.680330  0.902549  0.504906
B  0.378378  0.643315  0.846567  0.304486  0.698178
C  0.059088  0.551254  0.654128  0.086218  0.580523
D  0.482643  0.908782  0.717089  0.861414  0.865603
E  0.712761  0.720142  0.245750  0.739501  0.562714
F  0.231970  0.256622  0.952739  0.416191  0.466437
G  0.722226  0.763137  0.776198  0.820809  0.701521
H  0.065350  0.896922  0.532453  0.756854  0.587840

In [21]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.817689  0.624646  0.504906
B  0.643315  0.378378  0.698178
C  0.551254  0.059088  0.580523
D  0.908782  0.482643  0.865603
E  0.720142  0.712761  0.562714
F  0.256622  0.231970  0.466437
G  0.763137  0.722226  0.701521
H  0.896922  0.065350  0.587840

In [22]:
df1['Score6']=df1['Score1']-df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.624646  0.817689  0.680330  0.902549  0.504906 -0.193043
B  0.378378  0.643315  0.846567  0.304486  0.698178 -0.264937
C  0.059088  0.551254  0.654128  0.086218  0.580523 -0.492166
D  0.482643  0.908782  0.717089  0.861414  0.865603 -0.426140
E  0.712761  0.720142  0.245750  0.739501  0.562714 -0.007381
F  0.231970  0.256622  0.952739  0.416191  0.466437 -0.024652
G  0.722226  0.763137  0.776198  0.820809  0.701521 -0.040911
H  0.065350  0.896922  0.532453  0.756854  0.587840 -0.831572

In [23]:
 df1.drop('Score5',axis=1)

Score1    Score2    Score3    Score4    Score6
A  0.624646  0.817689  0.680330  0.902549 -0.193043
B  0.378378  0.643315  0.846567  0.304486 -0.264937
C  0.059088  0.551254  0.654128  0.086218 -0.492166
D  0.482643  0.908782  0.717089  0.861414 -0.426140
E  0.712761  0.720142  0.245750  0.739501 -0.007381
F  0.231970  0.256622  0.952739  0.416191 -0.024652
G  0.722226  0.763137  0.776198  0.820809 -0.040911
H  0.065350  0.896922  0.532453  0.756854 -0.831572

In [24]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.624646  0.817689  0.680330  0.902549  0.504906 -0.193043
B  0.378378  0.643315  0.846567  0.304486  0.698178 -0.264937
C  0.059088  0.551254  0.654128  0.086218  0.580523 -0.492166
D  0.482643  0.908782  0.717089  0.861414  0.865603 -0.426140
F  0.231970  0.256622  0.952739  0.416191  0.466437 -0.024652
G  0.722226  0.763137  0.776198  0.820809  0.701521 -0.040911
H  0.065350  0.896922  0.532453  0.756854  0.587840 -0.831572

In [27]:
df2={'ID':[101,102,103,107,176],'Name':['Prerana','Akanksha','Juhi','Anku','Deepak'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID      Name  Profit
0  101   Prerana      20
1  102  Akanksha      54
2  103      Juhi      56
3  107      Anku      87
4  176    Deepak     123

# Assessment
1. Create a null vector of size 10
2. Creat a null vector of size 10 but the fifth value should be one
3. Creat a vector with values raning from 10 to 65
4. Reverse the above vector
5. Create a 3x3 matrix with values ranging from 0to 8


In [29]:
import numpy as np

In [30]:
#1
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
#2
null_vector1 = np.zeros(10)
null_vector1[4]= 1
null_vector1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [37]:
#3
vector = np.arange(10,66)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [40]:
#4
vector[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [39]:
#4
rev_vector = np.arange(65,9,-1)
rev_vector

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [53]:
#5
matrix=np.arange(0,9)
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
matrix1=np.arange(0,9).reshape(3,3)
matrix1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
matrix2=np.arange(9).reshape(3,3)
matrix2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
x= np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
